// <auto-generated />
using CrudQualidade.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudQualidade.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230924182324_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("CrudQualidade.Domain.Entities.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peoples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            City = "Rio Verde",
                            Email = "lucas@email.com",
                            LastName = "Oliveira",
                            Name = "Lucas",
                            NumberPhone = "64123456879"
                        },
                        new
                        {
                            Id = 2,
                            Age = 44,
                            City = "Rio Verde",
                            Email = "marcia@email.com",
                            LastName = "Oliveira",
                            Name = "Márcia",
                            NumberPhone = "64123412342"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
